[tool.poetry]
name = "python-dynamodb"
version = "0.1.0"
description = ""
authors = ["daviico <daviidco@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.144"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
